name: Compile QMK with datew0`s keymap
on: [push]
jobs:
  build_firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: sudo apt update && sudo apt install gcc-arm-none-eabi make -y
        
      - name: Compile submodules
        run: make git-submodules
        
      - name: Compile QMK firmware
        run: make annepro2/c18:datew0
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: annepro2_c18_datew0.bin
          path: annepro2_c18_datew0.bin
